
Minimal reproduction of https://gitlab.haskell.org/ghc/ghc/-/issues/20918.
There is unexpected behaviour when C++ exception is thrown on Windows.
Even simple exceptions are not caught in this example.

```
ekrapie@SE-00025831 MINGW64 ~/programming/ghc-bug-20918
$ cabal v2-repl
Build profile: -w ghc-9.3.20220315 -O1
In order, the following will be built (use -v for more details):
 - throw-test-1.0.0 (lib) (ephemeral targets)
Preprocessing library for throw-test-1.0.0..
GHCi, version 9.3.20220315: https://www.haskell.org/ghc/  :? for help
Ok, one module loaded.
ghci> hello
"Hi"
equivalent_to_id test-throw 1
.
.
.
.
.
.
.
.
.
.
equivalent_to_id test-throw 1 caught 20
equivalent_to_id test-throw 2
.
.
.
.
.
.
.
.
.
.

Access violation in generated code when reading 0xffffffffffffffff

 Attempting to reconstruct a stack trace...

<..redacted..>

cabal.exe: repl failed for throw-test-1.0.0. The build process terminated with
exit code 11


ekrapie@SE-00025831 MINGW64 ~/programming/ghc-bug-20918 (main)
$ cabal v2-run
Up to date
equivalent_to_id test-throw 1
.
.
.
.
.
.
.
.
.
.
equivalent_to_id test-throw 1 caught 20
equivalent_to_id test-throw 2
.
.
.
.
.
.
.
.
.
.
equivalent_to_id test-throw 2 caught Test error.
.
.
.
.
.
.
.
.
.
.
"Hi"
"88.0"
"Bye"
```
